### PR TITLE
#106, BBOX tests can fail due to precision issues

### LINKED ISSUE #106: BBOX tests can fail due to precision issues
I have a dataset with just two EPSG 4326 points having the following coordinates:
- -66.16667 18.66667
- -66.71667 18.00126

The BBOX tests sample those points, get the overall bbox, and then use geomatrics-tgeotk Extends.evenlopeAsGML method to turn that into a BBOX usable for a filter. Unfortunately the method formats with just 2 decimal digits (definitely not enough for geographic coordinates) and ends up building a request as follows:

```
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="10" service="WFS"
                startIndex="0"
                version="2.0.0">
   <wfs:Query xmlns:ns97="http://www.opengeospatial.org/projects/initiatives/geoedgeplugfest"
              typeNames="ns97:port_p">
      <fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0">
         <fes:BBOX>
            <fes:ValueReference xmlns:tns="http://www.opengeospatial.org/projects/initiatives/geoedgeplugfest">tns:wkb_geometry</fes:ValueReference>
            <gml:Envelope xmlns:gml="http://www.opengis.net/gml/3.2" srsName="urn:ogc:def:crs:EPSG::4326">
               <gml:lowerCorner>-66.71 18</gml:lowerCorner>
               <gml:upperCorner>-66.16 18.66</gml:upperCorner>
            </gml:Envelope>
         </fes:BBOX>
      </fes:Filter>
   </wfs:Query>
</wfs:GetFeature>
```

The first point is not captured by the request as it sits slightly north of the bounds, while the second sits slightly west of the bounds. No features get captured, and the test end up failing.
Unfortunately the method does not allow customizing the precision, I guess the only approach would be to expand the extends a bit before formatting them. I'll follow up with a pull request.

### PR DESCRIPTION
**Pull request by aaime**
Fixes #106.

### CODE REVIEW

File: src/main/java/org/opengis/cite/iso19142/basic/filter/spatial/BBOXTests.java [hunk 1]
```diff
@@ -179,6 +179,21 @@ public void bboxWithDefaultExtent(ProtocolBinding binding, QName featureType) {
...
     }
 
+    /**
+     * Work around for Extents{@link #envelopeAsGML(Envelope)} only using 2 decimals
+     */
+    public Document envelopeAsGML(Envelope extent) {
+        double[] low = new double[extent.getDimension()];
+        double[] high = new double[extent.getDimension()];
+        for (int i = 0; i < extent.getDimension(); i++) {
+            low[i] = extent.getMinimum(i) - ENVELOPE_EXPANSION;
```
Comment (aaime) [inline src/main/java/org/opengis/cite/iso19142/basic/filter/spatial/BBOXTests.java]: Thinking out loud, maybe we want to also check if the CRS is geographic, and if so, make sure the result is within the normal coordinate limits.
